#! /usr/bin/env bash
# Build & then zip up the Chrome app
# for upload to the Chrome Web Store

# Check if we're on chrome-app branch
# h/t https://stackoverflow.com/questions/6245570/get-current-branch-name
if [ $(git rev-parse --abbrev-ref HEAD) = 'chrome-app' ]; then
    grunt build
    cd dist/
    rm index.html images/logo-no-bevel.png images/logo.png manifest.appcache
    zip -r lc.zip ./ --quiet && echo; echo 'Zipped dist directory successfully.'
else
    echo 'Must be on "chrome-app" branch to package the Chrome app.'
    exit 1
fi
